### ISSUE TITLE
MacOS Catalina support

### ISSUE THREAD

**Issue by mlostekk** [frankschlegel/core-image-by-example#2]
Arr, i would have loved to see this in action for one of my projects. Is it easily possible to make this compatible with Catalina?

**Comment by frankschlegel** [comment]
Hey @mlostekk, sorry for the late response!

I'm sorry for the current restrictions. I set this project up using SwiftUI 2 to also learn that on the side. However, all of the important code (capturing, filtering, previewing) is totally doable in Catalina (and earlier).

What are the pieces you are struggling with? Maybe I can help you adapt the workflow to not use SwiftUI and/or Combine.

**Comment by mlostekk** [comment]
Yep, I was able to extract the relevant code.

Thanks
